// <auto-generated />
namespace Clinica_Vet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ClinicaVet011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClinicaVet011));
        
        string IMigrationMetadata.Id
        {
            get { return "202301162211118_ClinicaVet011"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
