// <auto-generated />
namespace ClinicaVet.GestaoVeterinaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CriandoDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriandoDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202301102337456_CriandoDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
